const strings = {
    uz: {
        welcomeText: (name) => `Xush kelibsiz! 👋\n\n📊 Auditchi AI — bu shaxsiy moliyalaringizni avtomatik boshqaruvchi yordamchingiz.\n\n💡 Nimalar qila oladi?:\n💬 Sizni ovozingiz orqali tushunadi\n📊 Kirim va chiqimlaringizni tahlil qiladi\n🏷 Xarajatlaringizni toifalarga ajratadi\n✅ Moliyaviy intizomni shakllantirishga yordam beradi\n\n⏩ Davom etish uchun pastdagi tugma orqali telefon raqamingizni yuboring:`,
        requestPhoneBtn: "📱 Telefon raqamni yuborish",
        helpText: `Yordam:\nKirim va chiqimlarni kiritish uchun xabar matnidan foydalaning.\n\nKirim misoli:\n+150000 qarz qaytdi\n+500 mukofot\n\nChiqim misoli:\n-25000 taksi\n30000 bozorlik (faqat son yozsangiz ham chiqim hisoblanadi)\n\n/stats - Kunlik va oylik hisobotlar\n/balance - Hozirgi hisobingiz`,
        balance: (bal) => `💰 Sizning joriy balansingiz: *${bal.toLocaleString()}* so'm`,
        error: "Xatolik yuz berdi. Iltimos qayta urinib ko'ring.",
        statsFetchingError: "Hisobotni olishda xatolik yuz berdi.",
        statsTitle: "📊 *Hisobotlar*",
        todayTitle: "*📅 Bugun:*",
        monthTitle: (month) => `*📆 Shu oy (${month}):*`,
        incomeLabel: "Kirim",
        expenseLabel: "Chiqim",
        overallBalanceTitle: "💰 *Umumiy balans:*",
        invalidFormat: "Xato format. Iltimos, quyidagicha kiriting:\nKirim: +50000 oylik\nChiqim: -15000 ovqat (yoki 15000 ovqat)",
        transactionSuccess: (typeText, amount, desc, balance) => `${typeText} qabul qilindi: ${amount.toLocaleString()} so'm (${desc})\n💰 Joriy balans: ${balance.toLocaleString()} so'm`,
        incomeWord: "🟢 Kirim",
        expenseWord: "🔴 Chiqim",
        transactionSavingError: "Tranzaksiyani saqlashda xatolik yuz berdi.",
        languageSaved: "✅ Til saqlandi.",
        askName: "Ajoyib, tanishib olamiz, ismingiz nima?",
        registrationComplete: (name) => `Xush kelibsiz, ${name}! 🎉\n\nQuyidagi tugmalar orqali hisobotlarni olishingiz mumkin: ❤️`,
        regSuccess: (name) => `✅ Rahmat, ${name}! Ma'lumotlaringiz saqlandi.`,
        onboardingPrompt: `✅ Ro'yxatdan o'tib oldik.\n\n- Ming marta eshitgandan bir marta ishlatib ko'rgan afzal. Auditchi qanday ishlashini sinab ko'rishni istaysizmi?`,
        btnTryOut: "Ha, sinab ko'raman 💪",
        btnAlreadyKnow: "Men bilaman ✅",
        promptTryOutTarget: `Quyidagi harajatni audio yoki matn ko'rinishida yuboring:\n\nMasalan: "Taksiga 15,000 so'm xarajat qildim"`,
        promptAlreadyKnowTarget: `Ajoyib! O'z xarajat va daromadlaringizni tizimga kiritib borishingiz mumkin.`,
        dashboardBtn: "📈 Dashboard",
        balanceBtn: "💰 Balans",
        reportBtn: "📊 Hisobot",
        limitsBtn: "⚙️ Limitlar",
        adviceBtn: "💡 Maslahat",
        helpBtn: "❓ Yordam",
        voiceNotConfigured: "Ovozli tizim hozircha sozlanmagan. Iltimos matn shaklida yuboring.",
        voiceListening: "⏳ Ovozli xabar tinglanmoqda...",
        voiceTranslated: "Sizning ovozingiz:",
        limitsPrompt: "joriy oylik xarajat limingizni kiritish uchun shunchaki raqam yozib yuboring (Masalan: 5000000).\n\nO'chirish uchun 0 ni yuboring.",
        limitSaved: (limit) => limit === 0 ? "❗️ Oylik limit bekor qilindi." : `✅ Oylik limit o'rnatildi: ${limit.toLocaleString()} so'm`,
        limitExceededAlert: (expense, limit) => `⚠️ **DIQQAT! Limitdan oshib ketdingiz!**\n\nJoriy oydagi jami xarajatlaringiz: ${expense.toLocaleString()} so'm.\nBelgilangan limit: ${limit.toLocaleString()} so'm!`,
        dailyReminder: "Xayrli tong! ☀️\nBugun ham xarajat va daromadlaringizni hisobga olishni unutmang. Bot sizga qulaylik yaratishga doim tayyor."
    },
    ru: {
        welcomeText: (name) => `Добро пожаловать! 👋\n\n📊 Auditchi AI — это искусственный интеллект, автоматически управляющий вашими личными финансами.\n\n💡 Что он умеет?:\n💬 Понимает вас по голосу\n📊 Анализирует ваши доходы и расходы\n🏷 Распределяет расходы по категориям\n✅ Помогает формировать финансовую дисциплину\n\n⏩ Для продолжения отправьте свой номер телефона с помощью кнопки ниже:`,
        requestPhoneBtn: "📱 Отправить номер телефона",
        helpText: `Помощь:\nИспользуйте текстовые сообщения для ввода доходов и расходов.\n\nПример дохода:\n+150000 вернули долг\n+500 премия\n\nПример расхода:\n-25000 такси\n30000 продукты (если написать только число, это тоже расход)\n\n/stats - Дневные и месячные отчеты\n/balance - Ваш текущий баланс`,
        balance: (bal) => `💰 Ваш текущий баланс: *${bal.toLocaleString()}* сум`,
        error: "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
        statsFetchingError: "Ошибка при получении отчета.",
        statsTitle: "📊 *Отчеты*",
        todayTitle: "*📅 Сегодня:*",
        monthTitle: (month) => `*📆 В этом месяце (${month}):*`,
        incomeLabel: "Доход",
        expenseLabel: "Расход",
        overallBalanceTitle: "💰 *Общий баланс:*",
        invalidFormat: "Неверный формат. Пожалуйста, вводите так:\nДоход: +50000 зарплата\nРасход: -15000 еда (или 15000 еда)",
        transactionSuccess: (typeText, amount, desc, balance) => `${typeText} принят: ${amount.toLocaleString()} сум (${desc})\n💰 Текущий баланс: ${balance.toLocaleString()} сум`,
        incomeWord: "🟢 Доход",
        expenseWord: "🔴 Расход",
        transactionSavingError: "Ошибка при сохранении транзакции.",
        languageSaved: "✅ Язык сохранен.",
        askName: "Супер, давайте познакомимся, как вас зовут?",
        registrationComplete: (name) => `Добро пожаловать, ${name}! 🎉\n\nС помощью кнопок ниже вы можете получить отчеты: ❤️`,
        regSuccess: (name) => `✅ Спасибо, ${name}! Ваши данные сохранены.`,
        onboardingPrompt: `✅ Регистрация завершена.\n\n- Лучше один раз попробовать, чем тысячу раз услышать. Хотите протестировать, как работает Auditchi?`,
        btnTryOut: "Да, хочу попробовать 💪",
        btnAlreadyKnow: "Я уже знаю ✅",
        promptTryOutTarget: `Отправьте следующий расход в виде аудио или текста:\n\nНапример: "Потратил(а) 15,000 сум на такси"`,
        promptAlreadyKnowTarget: `Отлично! Вы можете начать записывать свои расходы и доходы.`,
        dashboardBtn: "📈 Дашборд",
        balanceBtn: "💰 Баланс",
        reportBtn: "📊 Отчет",
        limitsBtn: "⚙️ Лимиты",
        adviceBtn: "💡 Совет",
        helpBtn: "❓ Помощь",
        voiceNotConfigured: "Голосовая система пока не настроена. Пожалуйста, отправьте текстом.",
        voiceListening: "⏳ Слушаю голосовое сообщение...",
        voiceTranslated: "Ваш голос:",
        limitsPrompt: "чтобы ввести текущий ежемесячный лимит расходов, просто отправьте сумму (Пример: 5000000).\n\nЧтобы удалить лимит, отправьте 0.",
        limitSaved: (limit) => limit === 0 ? "❗️ Месячный лимит отменен." : `✅ Месячный лимит установлен: ${limit.toLocaleString()} сум`,
        limitExceededAlert: (expense, limit) => `⚠️ **ВНИМАНИЕ! Вы превысили лимит!**\n\nОбщие расходы за текущий месяц: ${expense.toLocaleString()} сум.\nУстановленный лимит: ${limit.toLocaleString()} сум!`,
        dailyReminder: "Доброе утро! ☀️\nНе забудьте сегодня учесть свои расходы и доходы. Бот всегда готов помочь вам с этим."
    }
};

module.exports = strings;
